# Generated by Django 5.1 on 2024-08-23 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_uservideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeOfTherapy', models.CharField(max_length=100)),
                ('problem', models.CharField(max_length=100)),
                ('sleepingHabits', models.CharField(max_length=100)),
                ('physicalHealth', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('providerGender', models.CharField(max_length=100)),
                ('dateOfBirth', models.DateField(max_length=100)),
                ('preferredLang', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userprofile')),
            ],
        ),
    ]
