# Generated by Django 5.1 on 2024-09-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userquestionnaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestionnaire',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
