# Generated by Django 5.1 on 2024-09-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_userquestionnaire_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestionnaire',
            name='dateOfBirth',
            field=models.CharField(max_length=100),
        ),
    ]
