# Generated by Django 5.1 on 2024-09-05 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_userquestionnaire_dateofbirth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquestionnaire',
            name='problem',
        ),
    ]
