# Generated by Django 5.1 on 2024-09-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_userquestionnaire_issue'),
    ]

    operations = [
        migrations.CreateModel(
            name='MHProfessional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('therapy_specification', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('dateOfBirth', models.CharField(max_length=100)),
                ('language1', models.CharField(max_length=100)),
                ('language2', models.CharField(max_length=100)),
                ('language3', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
            ],
        ),
    ]
