# Generated by Django 5.1 on 2024-09-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_userquestionnaire_diagnosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestionnaire',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
