# Generated by Django 5.1 on 2024-09-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_userquestionnaire_diagnosis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userquestionnaire',
            old_name='diagnosis',
            new_name='tags',
        ),
        migrations.AddField(
            model_name='mhprofessional',
            name='email',
            field=models.CharField(default='examplemail@gmail.com', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mhprofessional',
            name='phone',
            field=models.CharField(default='+91-2212331714', max_length=100),
            preserve_default=False,
        ),
    ]
